name: sequin

services:
  sequin:
    image: sequin/sequin:latest
    ports:
      - "7376:7376"
    environment:
      - PG_HOSTNAME=postgres
      - PG_DATABASE=sequin
      - PG_PORT=5432
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
      - PG_POOL_SIZE=20
      - SECRET_KEY_BASE=wDPLYus0pvD6qJhKJICO4dauYPXfO/Yl782Zjtpew5qRBDp7CZvbWtQmY0eB13If
      - VAULT_KEY=2Sig69bIpuSm2kv0VQfDekET2qy8qUZGI8v3/h3ASiY=
      - REDIS_URL=redis://redis:6379
      - CONFIG_FILE_PATH=/config/main.yml
    volumes:
      - ./sequin.yml:/config/main.yml
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sequin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sequin"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 2s
      start_interval: 1s

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--port", "6379"]
    volumes:
      - redis:/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./init/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  postgres: ~
  redis: ~
  rabbitmq: ~
